# Generated by Django 6.0.5 on 2026-05-31 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='題目內容')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='選項內容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否為正確答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz_app.question', verbose_name='所屬題目')),
            ],
            options={
                'verbose_name': '選項',
                'verbose_name_plural': '選項',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分數')),
                ('total_questions', models.IntegerField(verbose_name='總題數')),
                ('time_spent', models.IntegerField(verbose_name='耗時(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='測驗時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='玩家')),
            ],
            options={
                'verbose_name': '測驗紀錄',
                'verbose_name_plural': '測驗紀錄',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='是否答對')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.quizattempt', verbose_name='所屬測驗')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question', verbose_name='題目')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.choice', verbose_name='選擇的選項')),
            ],
            options={
                'verbose_name': '作答明細',
                'verbose_name_plural': '作答明細',
            },
        ),
    ]
