# Generated by Django 6.0.5 on 2026-05-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', '易'), ('medium', '中'), ('hard', '難')], default='medium', max_length=10, verbose_name='難易度'),
        ),
    ]
