# Generated by Django 6.0.5 on 2026-05-31 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_question_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '選項', 'verbose_name_plural': '選項'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '題目', 'verbose_name_plural': '題目'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name': '測驗紀錄', 'verbose_name_plural': '測驗紀錄'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': '作答明細', 'verbose_name_plural': '作答明細'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='是否為正確答案'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz_app.question', verbose_name='所屬題目'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='選項內容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='題目內容'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='測驗時間'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(verbose_name='分數'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_spent',
            field=models.IntegerField(verbose_name='耗時(秒)'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_questions',
            field=models.IntegerField(verbose_name='總題數'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizattempt', verbose_name='所屬測驗'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(verbose_name='是否答對'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question', verbose_name='題目'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.choice', verbose_name='選擇的選項'),
        ),
    ]
